const $=id=>document.getElementById(id);const STAT_NAMES=['strength','constitution','agility','intelligence','perception','willpower','charisma','luck'];let catalog=[],currentCard=null;
async function loadCatalog(){try{const r=await fetch('/cards-data.json');catalog=await r.json();}catch{catalog=[];}renderCatalog();if(catalog[0])loadCard(catalog[0]);else updatePreview(buildCard());}
function value(id){return $(id).value.trim();}function list(id){return value(id).split(',').map(x=>x.trim()).filter(Boolean);}
function effectsValue(){try{const parsed=JSON.parse(value('effects')||'[]');if(!Array.isArray(parsed))throw new Error();return parsed;}catch{return null;}}
function buildCard(){const statistics={};document.querySelectorAll('[data-stat]').forEach(i=>{const n=Number(i.value);if(n>0)statistics[i.dataset.stat]=n;});const effects=effectsValue()??currentCard?.effects??[{type:'damage',amount:10,damage_type:'physical'}];const resource=value('resource');const cost=Number($('cost').value||0);return{id:value('id'),name:value('name'),type:value('type'),rarity:value('rarity'),cost,resource,action_points_cost:Number($('actionPointsCost').value||0),mana_cost:resource==='mana'?cost:0,target:value('target'),description:value('description'),flavor:value('flavor'),image:value('image'),requirements:{statistics,races:list('races'),tags:list('requiredTags'),requires_cards:list('requiresCards'),min_level:Number($('minLevel').value||1)},effects,tags:[]};}
function renderPreview(card){const image=card.image?`<img src="${esc(card.image)}" onerror="this.parentElement.innerHTML='Immagine non trovata';">`:'IMMAGINE';$('cardPreview').innerHTML=`<div class="art">${image}</div><div class="meta"><span>${esc(card.type)} · ${esc(card.rarity)} · ${esc(card.target||'enemy')}</span><span class="cost-badge">${esc(card.resource==='mana'?`${card.cost} MANA + ${card.action_points_cost||1} PA`:`${card.action_points_cost||card.cost} PA`)}</span></div><h2>${esc(card.name||'Nome carta')}</h2><p>${esc(card.description||'Descrizione della carta.')}</p><p><em>${esc(card.flavor||'')}</em></p><div class="tags">${Object.entries(card.requirements.statistics||{}).map(([k,v])=>`<span>${esc(k)} ≥ ${v}</span>`).join('')}${(card.requirements.races||[]).map(x=>`<span>${esc(x)}</span>`).join('')}${(card.requirements.requires_cards||[]).map(x=>`<span>↳ ${esc(x)}</span>`).join('')}</div>`;$('jsonOutput').textContent=JSON.stringify(card,null,2);}
function updatePreview(card){currentCard=card;renderPreview(card);}
function loadCard(card){currentCard=JSON.parse(JSON.stringify(card));$('id').value=card.id||'';$('name').value=card.name||'';$('type').value=card.type||'skill';$('rarity').value=card.rarity||'common';$('cost').value=card.cost??1;$('resource').value=card.resource||'action_points';$('actionPointsCost').value=card.action_points_cost??1;$('target').value=card.target||'enemy';$('description').value=card.description||'';$('flavor').value=card.flavor||'';$('image').value=card.image||'';$('effects').value=JSON.stringify(card.effects||[],null,2);$('minLevel').value=card.requirements?.min_level??1;$('races').value=(card.requirements?.races||[]).join(', ');$('requiresCards').value=(card.requirements?.requires_cards||[]).join(', ');$('requiredTags').value=(card.requirements?.tags||[]).join(', ');document.querySelectorAll('[data-stat]').forEach(i=>i.value=card.requirements?.statistics?.[i.dataset.stat]??'');updatePreview(card);}
function renderCatalog(){$('catalog').innerHTML=catalog.map((c,i)=>`<div class="catalog-item"><div class="thumb">${c.image?`<img src="${esc(c.image)}">`:''}</div><div><strong>${esc(c.name)}</strong><small>${esc(c.id)} · ${esc(c.rarity)} · ${c.cost} ${esc(c.resource)}</small></div><button type="button" data-load="${i}">Apri</button></div>`).join('');document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadCard(catalog[Number(b.dataset.load)]));}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}
$('cardForm').addEventListener('submit',e=>{e.preventDefault();const card=buildCard();if(!card.id||!card.name)return alert('Inserisci ID e nome.');if(!effectsValue())return alert('Gli effetti devono essere JSON valido e contenere una lista.');catalog=[...catalog.filter(x=>x.id!==card.id),card];currentCard=card;renderCatalog();renderPreview(card);});
$('resetBtn').onclick=()=>{currentCard=null;$('cardForm').reset();document.querySelectorAll('[data-stat]').forEach(x=>x.value='');$('cost').value=1;$('actionPointsCost').value=1;$('minLevel').value=1;$('target').value='enemy';$('effects').value='[{"type":"damage","amount":10,"damage_type":"physical"}]';updatePreview(buildCard());};
$('copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('jsonOutput').textContent);$('copyBtn').textContent='Copiato ✓';setTimeout(()=>$('copyBtn').textContent='Copia JSON',1200);};
$('cardForm').addEventListener('input',()=>{const c=buildCard();if(effectsValue()!==null)updatePreview(c);});
const statBox=$('stats');statBox.innerHTML=STAT_NAMES.map(s=>`<label>${s}<input data-stat="${s}" type="number" min="0" placeholder="nessun requisito"></label>`).join('');$('effects').value='[{"type":"damage","amount":10,"damage_type":"physical"}]';loadCatalog();
