const qs=new URLSearchParams(location.search);const roomId=qs.get('room');const token=qs.get('token');let room=null;let filter='all';let busy=false;const $=id=>document.getElementById(id);function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));}
function showMessage(text){const m=$('message');m.textContent=text;m.classList.remove('hidden');setTimeout(()=>m.classList.add('hidden'),2600);}
function links(){if(!roomId||!token){$('message').textContent='Apri questa pagina dal link personale della partita PvP.';$('message').classList.remove('hidden');return false;}$('arenaLink').href=`/battle.html?room=${encodeURIComponent(roomId)}&token=${encodeURIComponent(token)}`;$('sheetLink').href=`/index.html?room=${encodeURIComponent(roomId)}&token=${encodeURIComponent(token)}`;return true;}
function cardImage(card){return card.image?`<img src="${esc(card.image)}" onerror="this.style.display='none'">`:'<span>IMMAGINE</span>';}
function render(){if(!room)return;const own=room.combatants[String(room.you_are)];$('characterName').textContent=own?.name||'Personaggio';$('characterInfo').textContent=own?`${own.status} · HP ${own.health}/${own.max_health} · Mana ${own.mana}/${own.max_mana}`:'';const d=room.deck||{known:[],deck:[],catalog:[]};$('knownCount').textContent=d.known.length;$('deckCount').textContent=d.deck.length;let cards=d.catalog||[];cards=cards.filter(c=>filter==='all'||(filter==='known'&&c.known)||(filter==='deck'&&c.in_deck)||(filter==='blocked'&&!c.learnable));$('catalog').innerHTML=cards.map(card=>{const blocked=!card.learnable&&!card.known;const status=card.in_deck?'NEL MAZZO':card.known?'CONOSCIUTA':card.learnable?'IMPARABILE':'BLOCCATA';let button='';if(blocked){button='<button disabled>Bloccata</button>';}else if(card.in_deck){button=`<button class="remove" data-card="${esc(card.id)}">Rimuovi dal mazzo</button>`;}else if(card.known){button=`<button data-card="${esc(card.id)}">Aggiungi al mazzo</button>`;}else{button=`<button data-learn="${esc(card.id)}">Impara e aggiungi</button>`;}const reasons=(card.blocked_reasons||[]).map(r=>`<div>• ${esc(r)}</div>`).join('');const req=card.learnable&&reasons?'':reasons;return `<article class="card-item ${blocked?'blocked':''}"><div class="art">${cardImage(card)}</div><div class="card-body"><div class="card-meta"><span>${esc(card.type)} · ${esc(card.rarity)}</span><span>${card.resource==='mana'?`${card.cost} MANA`:`${card.action_points_cost||card.cost} PA`}</span></div><h3>${esc(card.name)}</h3><p>${esc(card.description)}</p><div class="chips">${Object.entries(card.requirements?.statistics||{}).map(([k,v])=>`<span class="chip">${esc(k)} ≥ ${v}</span>`).join('')}${(card.requirements?.races||[]).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${req?`<div class="requirements"><b>REQUISITI</b>${req}</div>`:''}<div class="card-footer"><span class="status">${status}</span>${button}</div></div></article>`;}).join('')||'<section class="card"><p>Nessuna carta in questa categoria.</p></section>';
 document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>deckAction('deck_toggle',b.dataset.card));document.querySelectorAll('[data-learn]').forEach(b=>b.onclick=()=>deckAction('deck_learn',b.dataset.learn));}
async function refresh(){if(!links())return;try{const r=await fetch(`/api/pvp/${encodeURIComponent(roomId)}?token=${encodeURIComponent(token)}`);const data=await r.json();if(!r.ok)throw new Error(data.error||'Link non valido.');if(data.is_spectator||data.you_are==='spectator')throw new Error('Il mazzo è modificabile solo dal giocatore.');room=data;render();}catch(e){showMessage(e.message);}}
async function deckAction(action,cardId){if(busy)return;busy=true;try{const r=await fetch(`/api/pvp/${encodeURIComponent(roomId)}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action,card_id:cardId})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Operazione rifiutata.');room=data;render();showMessage(action==='deck_learn'?'Carta imparata e aggiunta al mazzo.': 'Mazzo aggiornato.');}catch(e){showMessage(e.message);}finally{busy=false;}}
document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');filter=tab.dataset.filter;render();});links();refresh();setInterval(refresh,1800);
