export function showSection(section){document.querySelectorAll(".section").forEach(e=>e.classList.add("hidden"));document.getElementById(`${section}Section`)?.classList.remove("hidden");}
export function activateSection(section){showSection(section);document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.section===section));}
export function initializeNavigation(){document.querySelectorAll(".nav-button").forEach(button=>button.addEventListener("click",()=>{if(!button.classList.contains("disabled")&&button.dataset.section)activateSection(button.dataset.section);}));activateSection("characterDescription");}
export function updateCharacterTitle(character){const title=document.getElementById("characterTitle");if(!title)return;title.textContent=`${character?.identity?.name||""} ${character?.identity?.surname||""}`.trim()||"Nuovo personaggio";}
export function renderLanguages(character){const list=document.getElementById("languagesList");if(!list)return;list.innerHTML="";if(!character.languages.length){const e=document.createElement("div");e.className="empty-language";e.textContent="Nessuna lingua conosciuta.";list.appendChild(e);return;}character.languages.forEach(language=>{const item=document.createElement("div");item.className="language-item";const name=document.createElement("div");name.className="language-name";name.textContent=language.name||"Lingua sconosciuta";item.appendChild(name);const levels=document.createElement("div");levels.className="language-level-values";addLanguageLevel(levels,"Comprensione",language.comprehension);addLanguageLevel(levels,"Parlato",language.speaking);addLanguageLevel(levels,"Scrittura",language.writing);item.appendChild(levels);list.appendChild(item);});}
function addLanguageLevel(container,label,value){const row=document.createElement("div");row.className="language-value-row";const text=document.createElement("span");text.textContent=label;const valueText=document.createElement("span");valueText.textContent=`${Math.round(Number(value||0)*100)}%`;row.append(text,valueText);container.appendChild(row);}
export function resetGeneration(){setProgress(0,"L'IA sta preparando il personaggio...");const name=document.getElementById("generationName");if(name)name.textContent="Generazione in corso...";["stepRace","stepIdentity","stepLanguages","stepAppearance","stepConsistency","stepComplete"].forEach(id=>{const e=document.getElementById(id);if(!e)return;e.classList.remove("active","completed");const s=e.querySelector("span");if(s)s.textContent="○";});}
export function setProgress(value,status){const bar=document.getElementById("progressBar"),text=document.getElementById("progressText"),state=document.getElementById("generationStatus");if(bar)bar.style.width=`${value}%`;if(text)text.textContent=`${value}%`;if(state)state.textContent=status;}
export function setGenerationStep(id,state){const e=document.getElementById(id);if(!e)return;e.classList.remove("active","completed");const s=e.querySelector("span");if(state==="active"){e.classList.add("active");if(s)s.textContent="◉";}if(state==="completed"){e.classList.add("completed");if(s)s.textContent="✓";}}
export function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
