const state={player:null,conversation:[],game:null,setupMode:null,campaign:null};
const messages=document.getElementById("messages"),input=document.getElementById("input"),send=document.getElementById("send"),status=document.getElementById("status"),info=document.getElementById("characterInfo"),gameState=document.getElementById("gameState"),questState=document.getElementById("questState"),setup=document.getElementById("setup"),setupTitle=document.getElementById("setupTitle"),setupDescription=document.getElementById("setupDescription"),setupInput=document.getElementById("setupInput"),setupContinue=document.getElementById("setupContinue"),setupGenerate=document.getElementById("setupGenerate");
async function api(path,options={}){const r=await fetch(path,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Errore HTTP "+r.status);return data}
function render(){messages.innerHTML="";if(!state.conversation.length){messages.innerHTML="<div class=\"empty-chat\">La campagna è pronta.<br><span>Scrivi cosa fa il tuo personaggio.</span></div>";return}for(const m of state.conversation){const el=document.createElement("div");el.className="message "+(m.role==="user"?"user":"ai");const label=document.createElement("div");label.className="message-label";label.textContent=m.role==="user"?"TU":"NARRATORE";el.appendChild(label);el.appendChild(document.createTextNode(m.content));messages.appendChild(el)}messages.scrollTop=messages.scrollHeight}
function renderInfo(){if(!state.player){info.textContent="Nessun protagonista.";return}const i=state.player.identity||{};info.innerHTML="<strong>"+escapeHtml(i.name||"Senza nome")+"</strong><br>"+escapeHtml(i.race||"razza sconosciuta")+" — età "+escapeHtml(i.age??"—")}
function renderGameState(){if(!state.game){gameState.textContent="—";questState.textContent="Nessuna quest attiva.";return}const c=state.game.conditions||{},g=state.game.game_state||{};gameState.innerHTML="HP "+(c.health??"—")+" / "+(c.max_health??"—")+"<br>Stamina "+(c.stamina??"—")+" / "+(c.max_stamina??"—")+"<br>Mana "+(c.mana??"—")+" / "+(c.max_mana??"—")+"<br>Turno "+(g.turn??"—")+"<br>Luogo "+escapeHtml(g.location??"non definito");const quests=(state.game.quests||[]).filter(q=>q&&q.status==="active");if(!quests.length){questState.textContent="Nessuna quest attiva.";return}questState.innerHTML=quests.map(q=>"<div class=\"quest-item\"><strong>"+escapeHtml(q.title||q.id)+"</strong><br><span>"+escapeHtml(q.description||"")+"</span></div>").join("")}
function escapeHtml(value){const div=document.createElement("div");div.textContent=String(value??"");return div.innerHTML}
async function loadState(){if(!state.player){state.game=null;renderGameState();return}state.game=await api("/api/game-state/"+state.player.id);renderGameState()}
async function loadHistory(){if(!state.player)return;const h=await api("/api/story-history/"+state.player.id);state.conversation=h.conversation||[];render()}
function showSetup(mode){state.setupMode=mode;setup.style.display="flex";input.disabled=true;send.disabled=true;if(mode==="player"){setupTitle.textContent="Crea il tuo personaggio";setupDescription.textContent="Questo sarà il tuo unico protagonista persistente. Le sue esperienze, relazioni, abilità e memoria continueranno tra le storie.";setupInput.placeholder="Descrivi il personaggio come vuoi. Se lasci vuoto, l'IA ne genererà uno.";setupContinue.textContent="Crea personaggio";setupGenerate.style.display="inline-flex"}else{setupTitle.textContent="Da dove vuoi iniziare?";setupDescription.textContent="Scrivi una premessa oppure lascia vuoto e lascia che l'IA generi una situazione iniziale. Verrà creato solo il punto di partenza: la storia continuerà dinamicamente.";setupInput.placeholder="Esempio: voglio iniziare in una piccola città fantasy cercando lavoro...";setupContinue.textContent="Inizia storia";setupGenerate.textContent="Genera storia per me";setupGenerate.style.display="inline-flex"}}
function hideSetup(){setup.style.display="none";input.disabled=false;send.disabled=false}
function showCampaignIntro(data){const campaign=data.campaign||{};const i=state.player?.identity||{};const intro=document.createElement("div");intro.className="campaign-intro";intro.innerHTML="<div class=\"page-label\">INIZIO DELLA STORIA</div><h2>"+escapeHtml(campaign.world_name||data.world?.name||"Il mondo")+"</h2><p>"+escapeHtml(campaign.world_lore||data.world?.description||"")+"</p><h3>"+escapeHtml(i.name||"Protagonista")+"</h3><p>"+escapeHtml(campaign.player_intro||[i.race,i.age?("Età "+i.age):"",i.appearance].filter(Boolean).join(" — "))+"</p>";messages.prepend(intro);hideSetup();messages.scrollTop=0}
async function loadPlayer(){const data=await api("/api/player");if(!data.exists){showSetup("player");status.textContent="Crea il tuo protagonista";return}state.player=data.player;renderInfo();const setupData=await api("/api/story-setup/"+state.player.id);if(!setupData.has_story){showSetup("story");status.textContent="Scegli come iniziare la storia"}else{hideSetup();await loadHistory();await loadState();status.textContent="Pronto"}}
setupContinue.addEventListener("click",async()=>{setupContinue.disabled=true;setupGenerate.disabled=true;status.textContent="L'IA sta preparando...";try{if(state.setupMode==="player"){const data=await api("/api/player",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:setupInput.value.trim()})});state.player=data.player;renderInfo();showSetup("story");setupInput.value="";status.textContent="Personaggio creato — scegli la storia"}else{const data=await api("/api/story/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({player_id:state.player.id,prompt:setupInput.value.trim()})});state.campaign=data.campaign||null;await loadHistory();await loadState();showCampaignIntro(data);status.textContent="Storia iniziata"}}
catch(e){alert(e.message);status.textContent="Errore"}finally{setupContinue.disabled=false;setupGenerate.disabled=false}});
setupGenerate.addEventListener("click",async()=>{setupInput.value="";setupContinue.click()});
document.getElementById("newStory").addEventListener("click",async()=>{if(!state.player)return;try{await api("/api/story-history/reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({character_id:state.player.id})});setupInput.value="";showSetup("story");state.conversation=[];state.game=null;render();renderGameState();status.textContent="Nuova storia pronta"}catch(e){alert(e.message)}});
document.getElementById("chatForm").addEventListener("submit",async e=>{e.preventDefault();const text=input.value.trim();if(!text||!state.player||send.disabled)return;state.conversation.push({role:"user",content:text});render();input.value="";send.disabled=true;status.textContent="Il mondo sta reagendo...";try{const result=await api("/api/story-turn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({character_id:state.player.id,message:text})});state.conversation=result.conversation||state.conversation;await loadState();render();status.textContent="Pronto"}catch(err){state.conversation.pop();render();alert("Errore: "+err.message);status.textContent="Errore"}finally{send.disabled=false;input.focus()}});
input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();document.getElementById("chatForm").requestSubmit()}});
loadPlayer().catch(e=>{status.textContent="Errore di connessione";alert(e.message)});
