const state={character:null,conversation:[],game:null};
const select=document.getElementById("characterSelect"),messages=document.getElementById("messages"),input=document.getElementById("input"),send=document.getElementById("send"),status=document.getElementById("status"),info=document.getElementById("characterInfo"),gameState=document.getElementById("gameState"),questState=document.getElementById("questState");
async function api(url,options){const r=await fetch(url,options);let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||"Errore HTTP "+r.status);return data}
function render(){messages.innerHTML="";if(!state.conversation.length){messages.innerHTML="<div class=\"empty-chat\">La storia è vuota.<br><span>Scrivi cosa fa il tuo personaggio per iniziare.</span></div>";return}for(const m of state.conversation){const el=document.createElement("div");el.className="message "+(m.role==="user"?"user":"ai");const label=document.createElement("div");label.className="message-label";label.textContent=m.role==="user"?"TU":"NARRATORE";el.appendChild(label);el.appendChild(document.createTextNode(m.content));messages.appendChild(el)}messages.scrollTop=messages.scrollHeight}
function renderInfo(){if(!state.character){info.textContent="Nessun personaggio selezionato.";return}const i=state.character.identity||{};info.textContent=(i.name||"Senza nome")+" — "+(i.race||"razza sconosciuta")+" — età "+(i.age??"—")}
function renderGameState(){if(!state.game){gameState.textContent="—";questState.textContent="Nessuna quest attiva.";return}const c=state.game.conditions||{},g=state.game.game_state||{};gameState.innerHTML="HP "+(c.health??"—")+" / "+(c.max_health??"—")+"<br>Stamina "+(c.stamina??"—")+" / "+(c.max_stamina??"—")+"<br>Mana "+(c.mana??"—")+" / "+(c.max_mana??"—")+"<br>Turno "+(g.turn??"—")+"<br>Luogo "+(g.location??"non definito");const quests=(state.game.quests||[]).filter(q=>q&&q.status==="active");if(!quests.length){questState.textContent="Nessuna quest attiva.";return}questState.innerHTML=quests.map(q=>{const done=(q.objectives||[]).filter(o=>o&&o.done).length,total=(q.objectives||[]).length;return "<div class=\"quest-item\"><strong>"+escapeHtml(q.title||q.id)+"</strong><br><span>"+escapeHtml(q.description||"")+"</span><br><small>"+done+"/"+total+" obiettivi</small></div>"}).join("")}
function escapeHtml(value){const div=document.createElement("div");div.textContent=String(value??"");return div.innerHTML}
async function loadGameState(){if(!state.character){state.game=null;renderGameState();return}state.game=await api("/api/game-state/"+state.character.id);renderGameState()}
async function selectCharacter(id){if(!id){state.character=null;state.conversation=[];state.game=null;render();renderInfo();renderGameState();status.textContent="Seleziona un personaggio";return}state.character=await api("/api/characters/"+id);const h=await api("/api/story-history/"+id);state.conversation=h.conversation||[];await loadGameState();render();renderInfo();status.textContent="Pronto — "+(state.character.identity?.name||"personaggio")}
async function loadCharacters(){const list=await api("/api/characters");select.innerHTML="<option value=\"\">Seleziona personaggio</option>";for(const item of list){const i=item.identity||{},o=document.createElement("option");o.value=item.id;o.textContent=(i.name||"Senza nome")+(i.surname?" "+i.surname:"")+" (#"+item.id+")";select.appendChild(o)}let local=null;try{local=JSON.parse(localStorage.getItem("ai-rpg-character")||"null")}catch{}if(local?.identity?.name&&!local.id){try{const saved=await api("/api/characters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(local)});local.id=saved.id;localStorage.setItem("ai-rpg-character",JSON.stringify(local))}catch(e){console.warn("Salvataggio automatico personaggio fallito:",e.message)}}if(local?.id&&Array.from(select.options).some(o=>o.value===String(local.id)))select.value=String(local.id);if(select.value)await selectCharacter(select.value);else status.textContent="Nessun personaggio selezionato"}
select.addEventListener("change",()=>selectCharacter(select.value).catch(e=>{status.textContent="Errore";alert(e.message)}));
document.getElementById("newStory").addEventListener("click",async()=>{if(!state.character)return alert("Seleziona prima un personaggio.");if(!confirm("Cancellare la storia di questo personaggio?"))return;await api("/api/story-history/reset",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({character_id:state.character.id})});state.conversation=[];await loadGameState();render();status.textContent="Nuova storia pronta";input.focus()});
document.getElementById("chatForm").addEventListener("submit",async e=>{e.preventDefault();const text=input.value.trim();if(!text||!state.character||send.disabled)return;state.conversation.push({role:"user",content:text});render();input.value="";send.disabled=true;status.textContent="L’IA sta pensando...";try{const result=await api("/api/story-turn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({character_id:state.character.id,message:text})});state.conversation=result.conversation||state.conversation;await loadGameState();render();status.textContent="Pronto"}catch(err){state.conversation.pop();render();alert("Errore: "+err.message);status.textContent="Errore"}finally{send.disabled=false;input.focus()}});
input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();document.getElementById("chatForm").requestSubmit()}});loadCharacters().catch(e=>{status.textContent="Errore di connessione";alert(e.message)});